### ISSUE TITLE
Reader stops after first batch

### ISSUE THREAD

**Issue by erichutchins** [domoritz/json2parquet#1]
https://github.com/domoritz/json2parquet/blob/1c46f9d6ebcb8d2b6067bcaa89bc55712528bca4/src/main.rs#L180

Thank you for writing these utilities! I was looking for precisely this capability. 

I was consistently only getting 1024 records in my output until I realized the `reader.next()` function is only getting called once here. It needs to be wrapped in a loop to consume all the batches,  right?

**Comment by domoritz** [comment]
You are absolutely right. I found that the JSON reader does not seem to implement the iterator interface. See https://github.com/apache/arrow-rs/issues/193

The code should be

```rust
    for batch in reader {
        match batch {
            Ok(batch) => writer.write(&batch)?,
            Err(error) => return Err(error.into()),
        }
    }
```

but it does not compile. 

<img width="1084" alt="Screen Shot 2021-05-06 at 19 46 05" src="https://user-images.githubusercontent.com/589034/117390829-b4229680-aea3-11eb-91d0-eb062065b29c.png">

I have the same problem in https://github.com/domoritz/json2arrow. 

Maybe what I should do is do a while loop here but I feel the JSON reader should be fixed instead.
